#!/usr/bin/env python3
"""
Generate `docs/mcp-reference.md` from the MCP server's own tool definitions.

The reference is generated rather than written because of a trap specific to this
codebase: a tool's docstring *is* the description the model reads. Hand-maintaining
a second copy in prose means the doc and the model's instructions can disagree, and
nothing would notice. Here there is one source — `mcp_server/tools.py` — and this
script renders it.

It introspects the server object in-process, so no HTTP server and no database are
needed; it works in CI.

    python scripts/dump_mcp_tools.py            # write docs/mcp-reference.md
    python scripts/dump_mcp_tools.py --check    # exit 1 if the file is stale

Run it after adding or changing a tool.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path
from typing import Any

_BACKEND = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_BACKEND))

from mcp_server.server import mcp  # noqa: E402  (needs the path above)

OUTPUT = _BACKEND.parent / "docs" / "mcp-reference.md"

BANNER = "<!-- Generated by backend/scripts/dump_mcp_tools.py. Do not edit by hand. -->"

PREAMBLE = f"""\
# MCP reference

{BANNER}

Every tool, resource and prompt served at `/mcp`, with the exact text the client
and model receive. Generated from `backend/mcp_server/`, so this page and the
agent's own instructions cannot drift apart.

New here? [Connecting a client](mcp-getting-started.md) covers the endpoint, the
rate limits and what to ask first. The reasoning behind the data — and what the
annual means do not say — is in [the design notes](mcp-server-plan.md).
"""



def type_of(schema: dict[str, Any]) -> str:
    """A readable type for one JSON Schema property."""
    if "const" in schema:
        # Just the value: it reads as a fixed value on its own, and appending
        # "(constant)" turns an array of one into `"annual"` (constant)[].
        return f"`{json.dumps(schema['const'])}`"
    # An enum is the whole point of the field, and rendering it as `string` cost a
    # careful reader the right conclusion: a reviewer read this page and reported
    # that the tools take an undocumented bare string. The model was always given
    # the enum — this document was not showing it.
    if "enum" in schema:
        return " | ".join(f"`{json.dumps(v)}`" for v in schema["enum"])
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        return f"[`{name}`](#{name.lower()})"
    if "anyOf" in schema:
        return " | ".join(type_of(s) for s in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        items = schema.get("items", {})
        return f"{type_of(items)}[]" if items else "array"
    if kind is None:
        return "any"
    return f"`{kind}`"


def render_fields(schema: dict[str, Any]) -> list[str]:
    """Render an object schema's properties as a definition list.

    A bullet list rather than a table: several defaults here are full sentences of
    provenance text, and those are the most useful part of the document for a human
    reader — they do not belong squeezed into a table cell.
    """
    props: dict[str, Any] = schema.get("properties", {})
    if not props:
        return ["*No fields.*"]

    required = set(schema.get("required", []))
    lines: list[str] = []
    for name, prop in props.items():
        bits = [f"- **`{name}`** — {type_of(prop)}"]
        bits.append("**required**" if name in required else "optional")
        lines.append(", ".join(bits))
        if desc := prop.get("description"):
            lines.append(f"  <br>{desc}")
        # A $ref's default is the whole nested object serialised — pages of
        # provenance text duplicating the shape's own section below. Skip it there.
        show_default = (
            "default" in prop
            and prop["default"] is not None
            and "const" not in prop
            and "$ref" not in prop
        )
        if show_default:
            default = prop["default"]
            rendered = default if isinstance(default, str) else json.dumps(default)
            lines.append(f"  <br>*Default:* {rendered}")
    return lines


def render_shape(name: str, schema: dict[str, Any], level: str) -> list[str]:
    lines = [f"{level} `{name}`", ""]
    if desc := schema.get("description"):
        lines += [desc, ""]
    lines += render_fields(schema)
    lines.append("")
    return lines


def render_defs(schema: dict[str, Any], skip: set[str]) -> list[str]:
    """Render the nested models a tool's output refers to, minus the shared ones."""
    defs = {k: v for k, v in schema.get("$defs", {}).items() if k not in skip}
    if not defs:
        return []
    lines = ["#### Shapes", ""]
    for name, sub in sorted(defs.items()):
        lines += render_shape(name, sub, "#####")
    return lines


def shared_defs(tools: list[Any]) -> dict[str, Any]:
    """Definitions that appear in more than one tool and are identical in each.

    Hoisting these is not tidying. Six tools each rendered their own
    `##### \`Provenance\`` heading, so the anchors came out as `#provenance`,
    `#provenance-1` … `#provenance-5` — while every `$ref` link rendered by
    `type_of` pointed at `#provenance`. Five of the six tools linked to a
    different tool's copy of the shape, and it looked like it worked because the
    destination was byte-identical.

    A definition that differs between tools stays where it is: the duplication is
    then carrying information, and the anchors are genuinely distinct.
    """
    seen: dict[str, list[Any]] = {}
    for tool in tools:
        for name, body in (tool.output_schema or {}).get("$defs", {}).items():
            seen.setdefault(name, []).append(body)
    return {
        name: bodies[0]
        for name, bodies in seen.items()
        if len(bodies) > 1 and all(b == bodies[0] for b in bodies)
    }


def render_tool(tool: Any, shared: set[str]) -> list[str]:
    ann = tool.annotations
    hints = []
    if ann is not None:
        if ann.read_only_hint:
            hints.append("read-only")
        if ann.open_world_hint is False:
            hints.append("closed-world (answers from this database, not the web)")

    # The title goes on its own line rather than after an em dash in the heading:
    # `### \`get_change\` — Change between periods` produces the anchor
    # #get-change-—-change-between-periods, which is fragile to paste and ugly in
    # a URL. An explicit {#slug} would fix the site and leak literal braces onto
    # GitHub, which reads the same file.
    lines = [f"### `{tool.name}`", ""]
    if tool.title:
        lines += [f"**{tool.title}**", ""]
    if hints:
        lines += [f"*{', '.join(hints)}*", ""]
    if tool.description:
        lines += [tool.description, ""]

    lines += ["#### Parameters", ""]
    inp = tool.input_schema or {}
    lines += ["*None.*", ""] if not inp.get("properties") else render_fields(inp) + [""]

    out = tool.output_schema
    if out:
        lines += ["#### Returns", ""]
        lines += render_fields(out)
        lines.append("")
        lines += render_defs(out, shared)
    return lines


async def build() -> str:
    lines = [PREAMBLE]

    # The instructions are the only model-facing text that is not attached to a
    # tool, resource or prompt — and the first thing a client receives. Leaving
    # them out made this reference incomplete in exactly the way it claims not to be.
    if instructions := (mcp.instructions or "").strip():
        lines += [
            "## Server instructions",
            "",
            "Returned in the `server/discover` result and put in front of the model once "
            "per connection, before any tool is called. Defined as `INSTRUCTIONS` in "
            "`backend/mcp_server/server.py`.",
            "",
        ]
        lines += [f"> {line}" if line else ">" for line in instructions.splitlines()]
        lines.append("")

    tools = sorted(await mcp.list_tools(), key=lambda t: t.name)
    shared = shared_defs(tools)
    lines += ["## Tools", "", "Verbs the *model* calls.", ""]
    # No count of what's *missing* — a hardcoded "seven more" is exactly the kind of
    # number that goes stale the first time a tool lands.
    lines.append(f"{len(tools)} tool{'s' if len(tools) != 1 else ''} served today. "
                 "Further tools are designed in `docs/mcp-server-plan.md`.\n")
    for tool in tools:
        lines.extend(render_tool(tool, set(shared)))

    # Each entry is its own subsection rather than a bullet: descriptions run to
    # several paragraphs, and a paragraph inside a list item breaks the list.
    if resources := await mcp.list_resources():
        lines += [
            "## Resources",
            "",
            "Documents the *client* loads and attaches, addressed by URI rather than "
            "called by name. Claude Desktop lists them in the composer under "
            "Connectors.",
            "",
        ]
        for r in sorted(resources, key=lambda r: str(r.uri)):
            lines += [f"### `{r.uri}`", ""]
            if r.title:
                lines += [f"**{r.title}**", ""]
            lines += [f"*{r.mime_type}*", ""] if r.mime_type else []
            if r.description:
                lines += [r.description, ""]

    if shared:
        lines += [
            "## Common shapes",
            "",
            "Objects several tools return, defined identically in each. Every "
            "`$ref` above links here.",
            "",
        ]
        for name, body in sorted(shared.items()):
            lines += render_shape(name, body, "###")

    if prompts := await mcp.list_prompts():
        lines += [
            "## Prompts",
            "",
            "Templates a *person* picks and fills in; the rendered message enters the "
            "conversation as if they had typed it. Arguments are plain named strings, "
            "not a schema.",
            "",
        ]
        for p in sorted(prompts, key=lambda p: p.name):
            lines += [f"### `{p.name}`", ""]
            if p.title:
                lines += [f"**{p.title}**", ""]
            if p.description:
                lines += [p.description, ""]
            if p.arguments:
                lines += ["#### Arguments", ""]
                for arg in p.arguments:
                    lines.append(
                        f"- **`{arg.name}`** — "
                        + ("**required**" if arg.required else "optional")
                    )
                    if arg.description:
                        lines.append(f"  <br>{arg.description}")
                lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    content = asyncio.run(build())
    check = "--check" in sys.argv

    if check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print(
                f"{OUTPUT.relative_to(_BACKEND.parent)} is out of date. "
                "Regenerate with: cd backend && python scripts/dump_mcp_tools.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.relative_to(_BACKEND.parent)} is up to date.")
        return 0

    OUTPUT.write_text(content)
    print(f"Wrote {OUTPUT.relative_to(_BACKEND.parent)} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
