#!/usr/bin/env python3
"""
Generate `docs/mcp-reference.md` from the MCP server's own tool definitions.

The reference is generated rather than written because of a trap specific to this
codebase: a tool's docstring *is* the description the model reads. Hand-maintaining
a second copy in prose means the doc and the model's instructions can disagree, and
nothing would notice. Here there is one source — `mcp_server/tools.py` — and this
script renders it.

It introspects the server object in-process, so no HTTP server and no database are
needed; it works in CI.

    python scripts/dump_mcp_tools.py            # write docs/mcp-reference.md
    python scripts/dump_mcp_tools.py --check    # exit 1 if the file is stale

Run it after adding or changing a tool.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path
from typing import Any

_BACKEND = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_BACKEND))

from mcp_server.server import mcp  # noqa: E402  (needs the path above)

OUTPUT = _BACKEND.parent / "docs" / "mcp-reference.md"

BANNER = "<!-- Generated by backend/scripts/dump_mcp_tools.py. Do not edit by hand. -->"

PREAMBLE = f"""\
# MCP reference

{BANNER}

The tools, resources and prompts served at `/mcp`. Every description below is the
text the client and model actually receive, so this document and the agent's own
instructions cannot drift apart — both come from `backend/mcp_server/`.

Endpoint, connection instructions and the rate limits are in the README; the
operational gotchas are in `CLAUDE.md`; the design and the roadmap for what is not
built yet are in `docs/mcp-server-plan.md`.

Regenerate with:

```bash
cd backend && python scripts/dump_mcp_tools.py
```
"""


def type_of(schema: dict[str, Any]) -> str:
    """A readable type for one JSON Schema property."""
    if "const" in schema:
        # Just the value: it reads as a fixed value on its own, and appending
        # "(constant)" turns an array of one into `"annual"` (constant)[].
        return f"`{json.dumps(schema['const'])}`"
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        return f"[`{name}`](#{name.lower()})"
    if "anyOf" in schema:
        return " | ".join(type_of(s) for s in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        items = schema.get("items", {})
        return f"{type_of(items)}[]" if items else "array"
    if kind is None:
        return "any"
    return f"`{kind}`"


def render_fields(schema: dict[str, Any]) -> list[str]:
    """Render an object schema's properties as a definition list.

    A bullet list rather than a table: several defaults here are full sentences of
    provenance text, and those are the most useful part of the document for a human
    reader — they do not belong squeezed into a table cell.
    """
    props: dict[str, Any] = schema.get("properties", {})
    if not props:
        return ["*No fields.*"]

    required = set(schema.get("required", []))
    lines: list[str] = []
    for name, prop in props.items():
        bits = [f"- **`{name}`** — {type_of(prop)}"]
        bits.append("**required**" if name in required else "optional")
        lines.append(", ".join(bits))
        if desc := prop.get("description"):
            lines.append(f"  <br>{desc}")
        # A $ref's default is the whole nested object serialised — pages of
        # provenance text duplicating the shape's own section below. Skip it there.
        show_default = (
            "default" in prop
            and prop["default"] is not None
            and "const" not in prop
            and "$ref" not in prop
        )
        if show_default:
            default = prop["default"]
            rendered = default if isinstance(default, str) else json.dumps(default)
            lines.append(f"  <br>*Default:* {rendered}")
    return lines


def render_defs(schema: dict[str, Any]) -> list[str]:
    """Render the nested models a tool's output refers to."""
    defs: dict[str, Any] = schema.get("$defs", {})
    if not defs:
        return []
    lines = ["#### Shapes", ""]
    for name, sub in sorted(defs.items()):
        lines.append(f"##### `{name}`")
        lines.append("")
        if desc := sub.get("description"):
            lines.append(desc)
            lines.append("")
        lines.extend(render_fields(sub))
        lines.append("")
    return lines


def render_tool(tool: Any) -> list[str]:
    ann = tool.annotations
    hints = []
    if ann is not None:
        if ann.read_only_hint:
            hints.append("read-only")
        if ann.open_world_hint is False:
            hints.append("closed-world (answers from this database, not the web)")

    lines = [f"### `{tool.name}`" + (f" — {tool.title}" if tool.title else ""), ""]
    if hints:
        lines += [f"*{', '.join(hints)}*", ""]
    if tool.description:
        lines += [tool.description, ""]

    lines += ["#### Parameters", ""]
    inp = tool.input_schema or {}
    lines += ["*None.*", ""] if not inp.get("properties") else render_fields(inp) + [""]

    out = tool.output_schema
    if out:
        lines += ["#### Returns", ""]
        lines += render_fields(out)
        lines.append("")
        lines += render_defs(out)
    return lines


async def build() -> str:
    lines = [PREAMBLE]

    tools = sorted(await mcp.list_tools(), key=lambda t: t.name)
    lines += ["## Tools", "", "Verbs the *model* calls.", ""]
    # No count of what's *missing* — a hardcoded "seven more" is exactly the kind of
    # number that goes stale the first time a tool lands.
    lines.append(f"{len(tools)} tool{'s' if len(tools) != 1 else ''} served today. "
                 "Further tools are designed in `docs/mcp-server-plan.md`.\n")
    for tool in tools:
        lines.extend(render_tool(tool))

    # Each entry is its own subsection rather than a bullet: descriptions run to
    # several paragraphs, and a paragraph inside a list item breaks the list.
    if resources := await mcp.list_resources():
        lines += [
            "## Resources",
            "",
            "Documents the *client* loads and attaches, addressed by URI rather than "
            "called by name. Claude Desktop lists them in the composer under "
            "Connectors.",
            "",
        ]
        for r in sorted(resources, key=lambda r: str(r.uri)):
            lines += [f"### `{r.uri}`" + (f" — {r.title}" if r.title else ""), ""]
            lines += [f"*{r.mime_type}*", ""] if r.mime_type else []
            if r.description:
                lines += [r.description, ""]

    if prompts := await mcp.list_prompts():
        lines += [
            "## Prompts",
            "",
            "Templates a *person* picks and fills in; the rendered message enters the "
            "conversation as if they had typed it. Arguments are plain named strings, "
            "not a schema.",
            "",
        ]
        for p in sorted(prompts, key=lambda p: p.name):
            lines += [f"### `{p.name}`" + (f" — {p.title}" if p.title else ""), ""]
            if p.description:
                lines += [p.description, ""]
            if p.arguments:
                lines += ["#### Arguments", ""]
                for arg in p.arguments:
                    lines.append(
                        f"- **`{arg.name}`** — "
                        + ("**required**" if arg.required else "optional")
                    )
                    if arg.description:
                        lines.append(f"  <br>{arg.description}")
                lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    content = asyncio.run(build())
    check = "--check" in sys.argv

    if check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print(
                f"{OUTPUT.relative_to(_BACKEND.parent)} is out of date. "
                "Regenerate with: cd backend && python scripts/dump_mcp_tools.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.relative_to(_BACKEND.parent)} is up to date.")
        return 0

    OUTPUT.write_text(content)
    print(f"Wrote {OUTPUT.relative_to(_BACKEND.parent)} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
