<script setup lang="ts">
/**
 * Scalar's API reference, embedded as a page.
 *
 * Loaded through `defineClientComponent` in ./index.ts — VitePress pre-renders
 * every page, and this component is not SSR-safe. Registering it any other way
 * fails the build, which is the good kind of failure.
 *
 * It reads `public/openapi.json`, a static file generated by
 * `backend/scripts/dump_openapi.py` and served alongside this page. Deliberately
 * not the live backend's /openapi.json: the published document is a filtered
 * copy containing only the Public routes, and a docs build should not depend on
 * a deploy being reachable.
 */
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { ApiReference } from '@scalar/api-reference'
import '@scalar/api-reference/style.css'
import { useData, withBase } from 'vitepress'

const { isDark } = useData()

const configuration = computed(() => ({
  url: withBase('/openapi.json'),
  // Scalar brings its own endpoint navigation; VitePress's sidebar is hidden on
  // this page by `layout: page`, so the two never compete.
  showSidebar: true,
  // Follow the site's toggle rather than keeping a second, separate one.
  darkMode: isDark.value,
  hideModels: true,
  // The try-it runner calls the Railway backend from this origin. Both are on
  // www.isosavi.com, so the request is same-origin as far as ALLOWED_ORIGIN is
  // concerned and needs no CORS change.
  hideClientButton: false,
}))

/**
 * Keep VitePress's router out of Scalar's internal navigation.
 *
 * VitePress listens for anchor clicks on `window` and handles same-page hash
 * links itself, resolving the target and scrolling to it. Scalar's endpoint
 * links use hashes like `#GET/api/network-stats/{year}/{variable}` — which is
 * not a valid CSS selector, so VitePress's handler throws on the braces and the
 * click dies there. The hash and the sidebar highlight update, the content pane
 * never moves. Searching still worked, because that path never goes through a
 * link click, which is what made it look like a rendering bug rather than a
 * routing one.
 *
 * Listening on the bubble phase, not capture: Scalar's own handlers sit on the
 * link and must run first. This only stops the event before it reaches window.
 */
const host = ref<HTMLElement | null>(null)

function keepHashLinksLocal(event: MouseEvent) {
  const link = (event.target as HTMLElement | null)?.closest?.('a')
  if (link?.getAttribute('href')?.startsWith('#')) event.stopPropagation()
}

onMounted(() => host.value?.addEventListener('click', keepHashLinksLocal))
onBeforeUnmount(() => host.value?.removeEventListener('click', keepHashLinksLocal))
</script>

<template>
  <div ref="host" class="scalar-host">
    <ApiReference :configuration="configuration" />
  </div>
</template>

<style>
/* Scalar ships a full-height app shell; inside a VitePress page it needs to be
   told where the page starts. 64px is the VitePress navbar. */
.scalar-host {
  height: calc(100vh - var(--vp-nav-height));
  overflow: hidden;
}
.scalar-host .scalar-api-reference {
  height: 100%;
}
</style>
