<script setup lang="ts">
/**
 * Scalar's API reference, embedded as a page.
 *
 * Loaded through `defineClientComponent` in ./index.ts — VitePress pre-renders
 * every page, and this component is not SSR-safe. Registering it any other way
 * fails the build, which is the good kind of failure.
 *
 * It reads `public/openapi.json`, a static file generated by
 * `backend/scripts/dump_openapi.py` and served alongside this page. Deliberately
 * not the live backend's /openapi.json: the published document is a filtered
 * copy containing only the Public routes, and a docs build should not depend on
 * a deploy being reachable.
 */
import { computed } from 'vue'
import { ApiReference } from '@scalar/api-reference'
import '@scalar/api-reference/style.css'
import { useData, withBase } from 'vitepress'

const { isDark } = useData()

const configuration = computed(() => ({
  url: withBase('/openapi.json'),
  // Scalar brings its own endpoint navigation; VitePress's sidebar is hidden on
  // this page by `layout: page`, so the two never compete.
  showSidebar: true,
  // Follow the site's toggle rather than keeping a second, separate one.
  darkMode: isDark.value,
  hideModels: true,
  // The try-it runner calls the Railway backend from this origin. Both are on
  // www.isosavi.com, so the request is same-origin as far as ALLOWED_ORIGIN is
  // concerned and needs no CORS change.
  hideClientButton: false,
}))

</script>

<!--
  `vp-raw` is not decoration — it is VitePress's own opt-out, and this page does
  not work without it.

  VitePress installs its click handler on `window` with `{ capture: true }` and
  calls `preventDefault()` on any same-origin link, then resolves the hash
  itself. Scalar's endpoint links are hashes like
  `#GET/api/stations/{year}/{variable}`, which is not a valid selector, so the
  click was cancelled and nothing scrolled — the URL and the sidebar highlight
  updated because those happen first. Search kept working because it never goes
  through a link click.

  `router.js` skips any link inside `.vp-raw` before it reaches that code, which
  hands the click back to Scalar. Stopping propagation in the container cannot
  achieve this: capture on `window` runs before any listener inside it.
-->
<template>
  <div class="scalar-host vp-raw">
    <ApiReference :configuration="configuration" />
  </div>
</template>

<style>
/* Scalar ships a full-height app shell; inside a VitePress page it needs to be
   told where the page starts. 64px is the VitePress navbar. */
.scalar-host {
  height: calc(100vh - var(--vp-nav-height));
  overflow: hidden;
}
.scalar-host .scalar-api-reference {
  height: 100%;
}
</style>
